package c_gen

import "core:fmt"
import "core:odin/ast"
import "core:odin/parser"
import "core:odin/tokenizer"
import "core:os"
import "core:slice"
import "core:strconv"
import "core:strings"

MARKER :: "// Code generated by wopt/c_gen. DO NOT EDIT."

Named :: struct {
	name: string,
	type: ^ast.Expr,
	file: ^ast.File,
	opaque: bool,
}

Proc :: struct {
	name: string,
	lit: ^ast.Proc_Lit,
	file: ^ast.File,
}

Model :: struct {
	pkg: ^ast.Package,
	prefix: string,
	func_prefix: string,
	named: [dynamic]Named,
	procs: [dynamic]Proc,
	slices: [dynamic]string,
	slice_elements: [dynamic]string,
	slice_odin_elements: [dynamic]string,
	errors: int,
}

main :: proc() {
	if len(os.args) != 2 {
		fmt.eprintln("usage: c_gen <odin-package-directory>")
		os.exit(2)
	}

	path := os.args[1]
	pkg, ok := parser.collect_package(path)
	if ok && pkg != nil {
		exclude_generated(pkg)
		ok = len(pkg.files) > 0 && parser.parse_package(pkg)
	}
	if !ok || pkg == nil {
		fmt.eprintln("c_gen: could not parse package", path)
		os.exit(1)
	}

	m := Model{pkg = pkg, prefix = c_prefix(pkg.name), func_prefix = strings.to_lower(pkg.name)}
	collect(&m)
	validate(&m)
	if m.errors != 0 {
		os.exit(1)
	}

	header := emit_header(&m)
	if m.errors != 0 {
		os.exit(1)
	}
	wrappers := emit_wrappers(&m)
	if m.errors != 0 { os.exit(1) }
	header_path := fmt.tprintf("%s/cgen.h", path)
	wrapper_path := fmt.tprintf("%s/cgen.odin", path)
	// Check both destinations before replacing either output.
	if !can_write_generated(header_path) || !can_write_generated(wrapper_path) { os.exit(1) }
	if !write_generated(header_path, header) || !write_generated(wrapper_path, wrappers) {
		os.exit(1)
	}
	fmt.println("generated", header_path)
	fmt.println("generated", wrapper_path)
}

exclude_generated :: proc(pkg: ^ast.Package) {
	// Stale generated syntax must not prevent regeneration.
	paths: [dynamic]string
	for name, file in pkg.files {
		if strings.has_prefix(file.src, MARKER) { append(&paths, name) }
	}
	for name in paths { delete_key(&pkg.files, name) }
}

c_prefix :: proc(name: string) -> string {
	if len(name) == 0 { return "CGen" }
	first, _ := strings.to_upper(name[:1])
	return fmt.tprintf("%s%s", first, name[1:])
}

collect :: proc(m: ^Model) {
	paths: [dynamic]string
	for path in m.pkg.files { append(&paths, path) }
	slice.sort(paths[:])
	for path in paths {
		file := m.pkg.files[path]
		if strings.has_prefix(file.src, MARKER) { continue }
		for stmt in file.decls {
			reject_conditional_exports(m, file, stmt)
			vd := stmt.derived_stmt.(^ast.Value_Decl) or_continue
			selected := has_tag(vd.attributes, "cabi")
			opaque := has_tag(vd.attributes, "cabi_opaque")
			if !selected && !opaque { continue }
			if vd.is_mutable {
				diagnostic(m, file, vd.pos, "selected variables are unsupported")
				continue
			}
			if len(vd.names) != 1 {
				diagnostic(m, file, vd.pos, "selected declarations must have one name")
				continue
			}
			name := vd.names[0].derived_expr.(^ast.Ident) or_continue
			decl_type := vd.type
			if decl_type == nil && len(vd.values) == 1 {
				if _, is_proc := vd.values[0].derived_expr.(^ast.Proc_Lit); !is_proc { decl_type = vd.values[0] }
			}
			if opaque {
				if selected { diagnostic(m, file, vd.pos, "choose cabi or cabi_opaque, not both") }
				if decl_type != nil {
					if st, is_struct := decl_type.derived_expr.(^ast.Struct_Type); is_struct && !st.is_raw_union && st.poly_params == nil {
						append(&m.named, Named{name = name.name, type = decl_type, file = file, opaque = true})
					} else { diagnostic(m, file, vd.pos, "cabi_opaque requires a non-polymorphic struct, not a union") }
				} else {
					diagnostic(m, file, vd.pos, "cabi_opaque requires a struct")
				}
				continue
			}
			if has_tag(vd.attributes, "cabi") && decl_type != nil {
				append(&m.named, Named{name = name.name, type = decl_type, file = file})
			}
			if has_tag(vd.attributes, "cabi") && len(vd.values) == 1 {
				lit := vd.values[0].derived_expr.(^ast.Proc_Lit) or_continue
				append(&m.procs, Proc{name = name.name, lit = lit, file = file})
			}
			if has_tag(vd.attributes, "cabi") && decl_type == nil && len(vd.values) != 1 {
				diagnostic(m, file, vd.pos, "selected declaration is not a supported type or procedure")
			}
		}
	}
}

has_tag :: proc(attrs: [dynamic]^ast.Attribute, wanted: string) -> bool {
	for a in attrs {
		for elem in a.elems {
			fv := elem.derived_expr.(^ast.Field_Value) or_continue
			key := fv.field.derived_expr.(^ast.Ident) or_continue
			lit := fv.value.derived_expr.(^ast.Basic_Lit) or_continue
			if key.name == "tag" && strings.trim(lit.tok.text, "\"") == wanted { return true }
		}
	}
	return false
}

diagnostic :: proc(m: ^Model, file: ^ast.File, pos: tokenizer.Pos, message: string) {
	m.errors += 1
	fmt.eprintf("%s:%d:%d: cabi: %s\n", file.fullpath, pos.line, pos.column, message)
}

validate :: proc(m: ^Model) {
	for n in m.named {
		if _, ok := n.type.derived_expr.(^ast.Ident); ok {
			diagnostic(m, n.file, n.type.pos, "plain type aliases are unsupported; use a distinct integer type")
		}
		if st, ok := n.type.derived_expr.(^ast.Struct_Type); ok && !n.opaque { expand_fields(st.fields) }
		if !n.opaque { validate_type(m, n.file, n.type, false) }
	}
	for p in m.procs {
		expand_fields(p.lit.type.params)
		if p.lit.type.results != nil { expand_fields(p.lit.type.results) }
		if p.lit.type.generic { diagnostic(m, p.file, p.lit.pos, "polymorphic procedures are unsupported") }
		for f in p.lit.type.params.list {
			if len(f.names) != 1 { diagnostic(m, p.file, f.pos, "procedure parameters must have exactly one name") }
			validate_type(m, p.file, f.type, false)
		}
		if p.lit.type.results != nil { for f in p.lit.type.results.list { validate_type(m, p.file, f.type, false) } }
	}
}

validate_type :: proc(m: ^Model, file: ^ast.File, e: ^ast.Expr, through_pointer: bool) {
	if e == nil { diagnostic(m, file, file.pos, "missing type") ; return }
	#partial switch t in e.derived_expr {
	case ^ast.Pointer_Type:
		validate_type(m, file, t.elem, true)
	case ^ast.Array_Type:
		if t.len != nil { diagnostic(m, file, t.pos, "fixed-size arrays are unsupported") }
		validate_type(m, file, t.elem, false)
	case ^ast.Ellipsis:
		validate_type(m, file, t.expr, through_pointer)
	case ^ast.Struct_Type:
		if t.is_raw_union || t.is_packed || t.align != nil || t.min_field_align != nil || t.max_field_align != nil || t.poly_params != nil {
			diagnostic(m, file, t.pos, "unions, packed/custom-aligned and polymorphic structs are unsupported")
		}
		if len(t.fields.list) == 0 { diagnostic(m, file, t.pos, "empty value structs are unsupported") }
		for f in t.fields.list {
			if len(f.names) != 1 { diagnostic(m, file, f.pos, "multiple or polymorphic field names are unsupported") ; continue }
			validate_type(m, file, f.type, false)
		}
	case ^ast.Enum_Type:
		if t.base_type != nil { validate_type(m, file, t.base_type, false) }
	case ^ast.Bit_Set_Type:
		if t.underlying != nil { validate_type(m, file, t.underlying, false) }
		_, _ = bit_set_enum(m, file, t)
	case ^ast.Distinct_Type:
		validate_type(m, file, t.type, false)
		base := c_builtin(strings.trim_space(source_text(file, t.type)))
		if !strings.has_prefix(base, "int") && !strings.has_prefix(base, "uint") {
			diagnostic(m, file, t.pos, "distinct types require a built-in integer base")
		}
	case ^ast.Union_Type:
		diagnostic(m, file, t.pos, "unions are unsupported")
	case ^ast.Proc_Type:
		diagnostic(m, file, t.pos, "callbacks and procedure types are unsupported")
	case ^ast.Poly_Type:
		diagnostic(m, file, t.pos, "polymorphic types are unsupported")
	case ^ast.Proc_Group:
		diagnostic(m, file, e.pos, "overload groups are unsupported")
	case ^ast.Map_Type, ^ast.Dynamic_Array_Type, ^ast.Fixed_Capacity_Dynamic_Array_Type, ^ast.Matrix_Type:
		diagnostic(m, file, e.pos, "this type form is unsupported")
	case:
		raw_type := strings.trim_space(source_text(file, e))
		if c_builtin(raw_type) != "" || raw_type == "string" { return }
		if n, ok := named(m, raw_type); ok {
			if n.opaque && !through_pointer { diagnostic(m, file, e.pos, fmt.tprintf("opaque type %s must cross through a pointer", raw_type)) }
			return
		}
		diagnostic(m, file, e.pos, fmt.tprintf("type %s is not a local annotated type", raw_type))
	}
}

// Normalize grouped fields and the typed compound-literal defaults used by wopt.
expand_fields :: proc(list: ^ast.Field_List) {
	fields: [dynamic]^ast.Field
	for f in list.list {
		if f.type == nil && f.default_value != nil {
			if lit, ok := f.default_value.derived_expr.(^ast.Comp_Lit); ok { f.type = lit.type }
		}
		if len(f.names) <= 1 { append(&fields, f); continue }
		for _, i in f.names {
			field := new(ast.Field)
			field^ = f^
			field.names = f.names[i:i+1]
			append(&fields, field)
		}
	}
	list.list = fields[:]
}

reject_conditional_exports :: proc(m: ^Model, file: ^ast.File, stmt: ^ast.Stmt, conditional := false) {
	if stmt == nil { return }
	#partial switch s in stmt.derived_stmt {
	case ^ast.When_Stmt:
		reject_conditional_exports(m, file, s.body, true)
		reject_conditional_exports(m, file, s.else_stmt, true)
	case ^ast.Block_Stmt:
		for child in s.stmts { reject_conditional_exports(m, file, child, conditional) }
	case ^ast.Value_Decl:
		if conditional && (has_tag(s.attributes, "cabi") || has_tag(s.attributes, "cabi_opaque")) {
			diagnostic(m, file, s.pos, "conditional exports are unsupported")
		}
	}
}

source_text :: proc(file: ^ast.File, e: ^ast.Expr) -> string {
	if e == nil { return "" }
	return file.src[e.pos.offset:e.end.offset]
}

named :: proc(m: ^Model, name: string) -> (Named, bool) {
	for n in m.named { if n.name == name { return n, true } }
	return {}, false
}

c_builtin :: proc(t: string) -> string {
	switch strings.trim_space(t) {
	case "bool": return "bool"
	case "i8": return "int8_t"
	case "u8": return "uint8_t"
	case "i16": return "int16_t"
	case "u16": return "uint16_t"
	case "i32": return "int32_t"
	case "u32": return "uint32_t"
	case "i64": return "int64_t"
	case "u64": return "uint64_t"
	case "int": return "intptr_t"
	case "uint": return "uintptr_t"
	case "f32": return "float"
	case "f64": return "double"
	case "rawptr": return "void *"
	}
	return ""
}

slice_key :: proc(t: string) -> string {
	a, _ := strings.replace_all(t, "^", "P")
	a, _ = strings.replace_all(a, "[]", "Slice")
	a, _ = strings.replace_all(a, "..", "Var")
	return a
}

c_type :: proc(m: ^Model, file: ^ast.File, e: ^ast.Expr) -> string {
	return c_type_text(m, file, strings.trim_space(source_text(file, e)))
}

c_type_field :: proc(m: ^Model, file: ^ast.File, e: ^ast.Expr, flags: ast.Field_Flags) -> string {
	if ell, is_ellipsis := e.derived_expr.(^ast.Ellipsis); is_ellipsis || .Ellipsis in flags {
		element := strings.trim_space(source_text(file, e))
		if is_ellipsis { element = strings.trim_space(source_text(file, ell.expr)) }
		key := register_slice(m, file, element)
		return fmt.tprintf("%s_Slice_%s", m.prefix, key)
	}
	return c_type(m, file, e)
}

odin_type_field :: proc(m: ^Model, file: ^ast.File, e: ^ast.Expr, flags: ast.Field_Flags) -> string {
	if ell, is_ellipsis := e.derived_expr.(^ast.Ellipsis); is_ellipsis || .Ellipsis in flags {
		key := slice_key(strings.trim_space(source_text(file, e)))
		if is_ellipsis { key = slice_key(strings.trim_space(source_text(file, ell.expr))) }
		return fmt.tprintf("%s_Slice_%s", m.prefix, key)
	}
	return odin_type_text(m, file, strings.trim_space(source_text(file, e)))
}

odin_type :: proc(m: ^Model, file: ^ast.File, e: ^ast.Expr) -> string {
	return odin_type_text(m, file, strings.trim_space(source_text(file, e)))
}

odin_type_text :: proc(m: ^Model, file: ^ast.File, t: string) -> string {
	switch t {
	case "bool", "i8", "u8", "i16", "u16", "i32", "u32", "i64", "u64", "int", "uint", "f32", "f64", "rawptr":
		return t
	case "string": return fmt.tprintf("%s_String", m.prefix)
	}
	if strings.has_prefix(t, "^") { return fmt.tprintf("^%s", odin_type_text(m, file, strings.trim_space(t[1:]))) }
	if strings.has_prefix(t, "[]") || strings.has_prefix(t, "..") { return fmt.tprintf("%s_Slice_%s", m.prefix, slice_key(t[2:])) }
	if n, ok := named(m, t); ok { return fmt.tprintf("%s_%s", m.prefix, n.name) }
	return t
}

c_type_text :: proc(m: ^Model, file: ^ast.File, t: string) -> string {
	if b := c_builtin(t); b != "" { return b }
	if t == "string" { return fmt.tprintf("%s_String", m.prefix) }
	if strings.has_prefix(t, "^") { return fmt.tprintf("%s *", c_type_text(m, file, strings.trim_space(t[1:]))) }
	if strings.has_prefix(t, "[]") || strings.has_prefix(t, "..") {
		key := register_slice(m, file, t[2:])
		return fmt.tprintf("%s_Slice_%s", m.prefix, key)
	}
	if n, ok := named(m, t); ok {
		return fmt.tprintf("%s_%s", m.prefix, n.name)
	}
	return t
}

register_slice :: proc(m: ^Model, file: ^ast.File, element: string) -> string {
	element_text := strings.trim_space(element)
	key := slice_key(element_text)
	for existing in m.slices {
		if existing == key { return key }
	}
	element_c := element_c_type(m, file, element_text)
	element_odin := element_odin_type(m, file, element_text)
	append(&m.slices, key)
	append(&m.slice_elements, element_c)
	append(&m.slice_odin_elements, element_odin)
	return key
}

element_c_type :: proc(m: ^Model, file: ^ast.File, element: string) -> string {
	if strings.has_prefix(element, "[]") || strings.has_prefix(element, "..") {
		key := register_slice(m, file, element[2:])
		return fmt.tprintf("%s_Slice_%s", m.prefix, key)
	}
	return c_type_text(m, file, element)
}

element_odin_type :: proc(m: ^Model, file: ^ast.File, element: string) -> string {
	if strings.has_prefix(element, "[]") || strings.has_prefix(element, "..") {
		key := register_slice(m, file, element[2:])
		return fmt.tprintf("%s_Slice_%s", m.prefix, key)
	}
	return odin_type_text(m, file, element)
}

emit_header :: proc(m: ^Model) -> string {
	for n in m.named {
		if n.opaque { continue }
		#partial switch t in n.type.derived_expr {
		case ^ast.Struct_Type:
			for f in t.fields.list { _ = c_type(m, n.file, f.type) }
		}
	}
	for p in m.procs {
		for f in p.lit.type.params.list { _ = c_type_field(m, p.file, f.type, f.flags) }
		if p.lit.type.results != nil { for f in p.lit.type.results.list { _ = c_type(m, p.file, f.type) } }
	}
	b: strings.Builder
	fmt.sbprintln(&b, MARKER)
	guard, _ := strings.to_upper(fmt.tprintf("%s_CGEN_H", m.prefix))
	fmt.sbprintf(&b, "#ifndef %s\n#define %s\n", guard, guard)
	fmt.sbprintln(&b, "#include <stdint.h>")
	fmt.sbprintln(&b, "#include <stddef.h>")
	fmt.sbprintln(&b, "#include <stdbool.h>")
	fmt.sbprintln(&b, "")
	fmt.sbprintf(&b, "typedef struct %s_String {{ const uint8_t *data; uintptr_t len; }} %s_String;\n", m.prefix, m.prefix)
	for n in m.named {
		if _, is_struct := n.type.derived_expr.(^ast.Struct_Type); is_struct {
			fmt.sbprintf(&b, "typedef struct %s_%s %s_%s;\n", m.prefix, n.name, m.prefix, n.name)
		}
	}
	for n in m.named {
		if n.opaque { continue }
		#partial switch t in n.type.derived_expr {
		case ^ast.Struct_Type:
			continue
		case ^ast.Distinct_Type:
			fmt.sbprintf(&b, "typedef %s %s_%s;\n", c_type(m, n.file, t.type), m.prefix, n.name)
		case ^ast.Enum_Type:
			base := "intptr_t"
			if t.base_type != nil { base = c_type(m, n.file, t.base_type) }
			fmt.sbprintf(&b, "typedef %s %s_%s;\n", base, m.prefix, n.name)
			value := 0
			for e in t.fields { value = emit_enum_c(&b, m, n, e, value) }
		case ^ast.Bit_Set_Type:
			et, enum_file := bit_set_enum(m, n.file, t)
			if et == nil { continue }
			low, high := enum_range(m, enum_file, et)
			bits := high - low + 1
			base := "uint8_t"
			if bits > 8 { base = "uint16_t" }
			if bits > 16 { base = "uint32_t" }
			if bits > 32 { base = "uint64_t" }
			if bits > 64 { diagnostic(m, n.file, t.pos, "bit sets wider than 64 bits are unsupported") }
			if t.underlying != nil { base = c_type(m, n.file, t.underlying) }
			fmt.sbprintf(&b, "typedef %s %s_%s;\n", base, m.prefix, n.name)
			value := 0
			enum_named := n
			enum_named.file = enum_file
			for e in et.fields { value = emit_bit_c(&b, m, enum_named, e, value, base, low) }
		case:
			fmt.sbprintf(&b, "typedef %s %s_%s;\n", c_type(m, n.file, n.type), m.prefix, n.name)
		}
	}
	for s, i in m.slices { fmt.sbprintf(&b, "typedef struct %s_Slice_%s {{ const %s *data; uintptr_t len; }} %s_Slice_%s;\n", m.prefix, s, m.slice_elements[i], m.prefix, s) }
	states := make(map[string]int)
	for n in m.named { emit_struct_c(&b, m, n, &states) }
	for p in m.procs {
		if p.lit.type.results != nil && len(p.lit.type.results.list) > 1 {
			fmt.sbprintf(&b, "typedef struct %s_%s_Result {{\n", m.prefix, p.name)
			for f, i in p.lit.type.results.list { fmt.sbprintf(&b, "    %s r%d;\n", c_type(m, p.file, f.type), i) }
			fmt.sbprintf(&b, "}} %s_%s_Result;\n", m.prefix, p.name)
		}
	}
	fmt.sbprintln(&b, "")
	for p in m.procs { emit_proc_decl(&b, m, p) }
	fmt.sbprintln(&b, "#endif")
	return strings.to_string(b)
}

// Struct pointers need only forward declarations; by-value fields need definitions.
emit_struct_c :: proc(b: ^strings.Builder, m: ^Model, n: Named, states: ^map[string]int) {
	if n.opaque || states^[n.name] == 2 { return }
	st, is_struct := n.type.derived_expr.(^ast.Struct_Type)
	if !is_struct { return }
	if states^[n.name] == 1 {
		diagnostic(m, n.file, n.type.pos, "recursive by-value struct")
		return
	}
	states^[n.name] = 1
	for f in st.fields.list {
		if dep, ok := named(m, strings.trim_space(source_text(n.file, f.type))); ok { emit_struct_c(b, m, dep, states) }
	}
	fmt.sbprintf(b, "struct %s_%s {{\n", m.prefix, n.name)
	for f in st.fields.list { emit_field_c(b, m, n.file, f) }
	fmt.sbprintln(b, "};")
	states^[n.name] = 2
}

bit_set_enum :: proc(m: ^Model, file: ^ast.File, t: ^ast.Bit_Set_Type) -> (^ast.Enum_Type, ^ast.File) {
	if et, ok := t.elem.derived_expr.(^ast.Enum_Type); ok { return et, file }
	if n, ok := named(m, strings.trim_space(source_text(file, t.elem))); ok {
		if et, is_enum := n.type.derived_expr.(^ast.Enum_Type); is_enum { return et, n.file }
	}
	diagnostic(m, file, t.pos, "bit sets require an inline enum or local annotated enum")
	return nil, file
}

enum_range :: proc(m: ^Model, file: ^ast.File, et: ^ast.Enum_Type) -> (low, high: int) {
	low, high = max(int), min(int)
	value := 0
	for e in et.fields {
		if fv, ok := e.derived_expr.(^ast.Field_Value); ok {
			parsed, valid := strconv.parse_int(strings.trim_space(source_text(file, fv.value)))
			if !valid { diagnostic(m, file, e.pos, "enum values must be integer literals") }
			value = parsed
		}
		low, high = min(low, value), max(high, value)
		value += 1
	}
	if len(et.fields) == 0 { diagnostic(m, file, et.pos, "empty bit-set enums are unsupported"); return 0, 0 }
	return
}

emit_field_c :: proc(b: ^strings.Builder, m: ^Model, file: ^ast.File, f: ^ast.Field) {
	if len(f.names) != 1 { return }
	name, ok := f.names[0].derived_expr.(^ast.Ident)
	if !ok { return }
	fmt.sbprintf(b, "    %s %s;\n", c_type(m, file, f.type), name.name)
}

emit_enum_c :: proc(b: ^strings.Builder, m: ^Model, n: Named, e: ^ast.Expr, current: int) -> int {
	name := ""
	value := current
	#partial switch x in e.derived_expr {
	case ^ast.Ident: name = x.name
	case ^ast.Field_Value:
		name = x.field.derived_expr.(^ast.Ident).name
		literal := strings.trim_space(source_text(n.file, x.value))
		parsed, ok := strconv.parse_int(literal)
		if !ok { diagnostic(m, n.file, x.value.pos, fmt.tprintf("enum value %s is not an integer literal", literal)) }
		value = parsed
	}
	if name != "" { fmt.sbprintf(b, "#define %s_%s_%s ((%s_%s)(%d))\n", m.prefix, n.name, name, m.prefix, n.name, value) }
	return value + 1
}

emit_bit_c :: proc(b: ^strings.Builder, m: ^Model, n: Named, e: ^ast.Expr, current: int, base: string, low: int) -> int {
	name := ""
	value := current
	#partial switch x in e.derived_expr {
	case ^ast.Ident: name = x.name
	case ^ast.Field_Value:
		name = x.field.derived_expr.(^ast.Ident).name
		literal := strings.trim_space(source_text(n.file, x.value))
		parsed, ok := strconv.parse_int(literal)
		if !ok { diagnostic(m, n.file, x.value.pos, fmt.tprintf("bit-set value %s is not an integer literal", literal)) }
		value = parsed
	}
	literal := bit_literal(base)
	if name != "" { fmt.sbprintf(b, "#define %s_%s_%s ((%s_%s)(%s << %d))\n", m.prefix, n.name, name, m.prefix, n.name, literal, value-low) }
	return value + 1
}

bit_literal :: proc(base: string) -> string {
	switch base {
	case "uint8_t", "int8_t": return "UINT8_C(1)"
	case "uint16_t", "int16_t": return "UINT16_C(1)"
	case "uint32_t", "int32_t": return "UINT32_C(1)"
	case "uint64_t", "int64_t": return "UINT64_C(1)"
	}
	return "UINT64_C(1)"
}

emit_proc_decl :: proc(b: ^strings.Builder, m: ^Model, p: Proc) {
	t := p.lit.type
	fmt.sbprintf(b, "%s %s_%s(", result_c_type(m, p), m.func_prefix, p.name)
	first := true
	for f in t.params.list {
		if len(f.names) != 1 { continue }
		if !first { fmt.sbprint(b, ", ") }; first = false
		name := f.names[0].derived_expr.(^ast.Ident) or_continue
		ct := c_type_field(m, p.file, f.type, f.flags)
		fmt.sbprintf(b, "%s %s", ct, name.name)
	}
	if first { fmt.sbprint(b, "void") }
	fmt.sbprintln(b, ");")
}

result_c_type :: proc(m: ^Model, p: Proc) -> string {
	if p.lit.type.results == nil || len(p.lit.type.results.list) == 0 { return "void" }
	if len(p.lit.type.results.list) == 1 { return c_type(m, p.file, p.lit.type.results.list[0].type) }
	return fmt.tprintf("%s_%s_Result", m.prefix, p.name)
}

emit_wrappers :: proc(m: ^Model) -> string {
	b: strings.Builder
	fmt.sbprintln(&b, MARKER)
	fmt.sbprintf(&b, "package %s\n", m.pkg.name)
	fmt.sbprintln(&b, "")
	fmt.sbprintln(&b, "import \"base:runtime\"")
	fmt.sbprintln(&b, "")
	fmt.sbprintf(&b, "%s_String :: struct {{ data: ^u8, len: uintptr }}\n", m.prefix)
	for s, i in m.slices { fmt.sbprintf(&b, "%s_Slice_%s :: struct {{ data: ^%s, len: uintptr }}\n", m.prefix, s, m.slice_odin_elements[i]) }
	for n in m.named {
		fmt.sbprintf(&b, "%s_%s :: %s\n", m.prefix, n.name, n.name)
	}
	for p in m.procs {
		if p.lit.type.results != nil && len(p.lit.type.results.list) > 1 {
			fmt.sbprintf(&b, "%s_%s_Result :: struct {{", m.prefix, p.name)
			for f, i in p.lit.type.results.list { fmt.sbprintf(&b, " r%d: %s,", i, odin_type_text(m, p.file, strings.trim_space(source_text(p.file, f.type)))) }
			fmt.sbprintln(&b, " }")
		}
	}
	for p in m.procs { emit_wrapper(&b, m, p) }
	return strings.to_string(b)
}

emit_wrapper :: proc(b: ^strings.Builder, m: ^Model, p: Proc) {
	t := p.lit.type
	fmt.sbprintf(b, "\n@(export, link_name=\"%s_%s\")\ncgen_export_%s :: proc \"c\" (", m.func_prefix, p.name, p.name)
	first := true
	for f in t.params.list {
		if len(f.names) != 1 { continue }
		if !first { fmt.sbprint(b, ", ") }; first = false
		id := f.names[0].derived_expr.(^ast.Ident) or_continue
		fmt.sbprintf(b, "%s: %s", id.name, odin_type_field(m, p.file, f.type, f.flags))
	}
	fmt.sbprint(b, ")")
	if t.results != nil && len(t.results.list) > 0 {
		if len(t.results.list) == 1 { fmt.sbprintf(b, " -> %s", odin_type(m, p.file, t.results.list[0].type)) }
		else { fmt.sbprintf(b, " -> %s_%s_Result", m.prefix, p.name) }
	}
	fmt.sbprintln(b, " {")
	fmt.sbprintln(b, "    context = runtime.default_context()")
	call := fmt.tprintf("%s(", p.name)
	first = true
	after_variadic := false
	for f in t.params.list {
		if len(f.names) != 1 { continue }
		id := f.names[0].derived_expr.(^ast.Ident) or_continue
		if !first { call = fmt.tprintf("%s, ", call) }; first = false
		if after_variadic { call = fmt.tprintf("%s%s = ", call, id.name) }
		call = fmt.tprintf("%s%s", call, wrapper_arg(m, p.file, f.type, id.name, f.flags))
		if _, ellipsis := f.type.derived_expr.(^ast.Ellipsis); ellipsis || .Ellipsis in f.flags { after_variadic = true }
	}
	call = fmt.tprintf("%s)", call)
	if t.results == nil || len(t.results.list) == 0 { fmt.sbprintf(b, "    %s\n", call) }
	else if len(t.results.list) == 1 {
		fmt.sbprintf(b, "    result := %s\n", call)
		fmt.sbprintf(b, "    return %s\n", wrapper_return(m, p.file, t.results.list[0].type, "result"))
	}
	else {
		parts := result_fields(t.results.list)
		fmt.sbprintf(b, "    %s := %s\n", parts, call)
		fields := ""
		for f, i in t.results.list {
			if i > 0 { fields = fmt.tprintf("%s, ", fields) }
			fields = fmt.tprintf("%s%s", fields, wrapper_return(m, p.file, f.type, fmt.tprintf("r%d", i)))
		}
		fmt.sbprintf(b, "    return %s_%s_Result{{%s}}\n", m.prefix, p.name, fields)
	}
	fmt.sbprintln(b, "}")
}

wrapper_arg :: proc(m: ^Model, file: ^ast.File, e: ^ast.Expr, name: string, flags: ast.Field_Flags) -> string {
	t := strings.trim_space(source_text(file, e))
	if ell, is_ellipsis := e.derived_expr.(^ast.Ellipsis); is_ellipsis || .Ellipsis in flags {
		if is_ellipsis { t = strings.trim_space(source_text(file, ell.expr)) }
		return fmt.tprintf("..(([^]%s)(%s.data)[:int(%s.len)])", t, name, name)
	}
	if t == "string" { return fmt.tprintf("string(([^]u8)(%s.data)[:int(%s.len)])", name, name) }
	if strings.has_prefix(t, "[]") { return fmt.tprintf("([^]%s)(%s.data)[:int(%s.len)]", strings.trim_space(t[2:]), name, name) }
	return name
}

wrapper_return :: proc(m: ^Model, file: ^ast.File, e: ^ast.Expr, call: string) -> string {
	t := strings.trim_space(source_text(file, e))
	if t == "string" { return fmt.tprintf("%s_String{{data = cast(^u8)raw_data(%s), len = uintptr(len(%s))}}", m.prefix, call, call) }
	if strings.has_prefix(t, "[]") {
		key := slice_key(t[2:])
		element := odin_type_text(m, file, strings.trim_space(t[2:]))
		return fmt.tprintf("%s_Slice_%s{{data = cast(^%s)raw_data(%s), len = uintptr(len(%s))}}", m.prefix, key, element, call, call)
	}
	return call
}

result_fields :: proc(fields: []^ast.Field) -> string {
	res := ""
	for i in 0..<len(fields) { if i > 0 { res = fmt.tprintf("%s, ", res) }; res = fmt.tprintf("%s r%d", res, i) }
	return res
}

can_write_generated :: proc(path: string) -> bool {
	if old, err := os.read_entire_file(path, context.temp_allocator); err == nil {
		if !strings.has_prefix(string(old), MARKER) {
			fmt.eprintf("c_gen: refusing to overwrite unmarked file %s\n", path)
			return false
		}
	} else if err != os.Error(os.General_Error.Not_Exist) {
		fmt.eprintf("c_gen: reading %s: %v\n", path, err)
		return false
	}
	return true
}

write_generated :: proc(path, data: string) -> bool {
	if err := os.write_entire_file(path, data); err != nil {
		fmt.eprintf("c_gen: writing %s: %v\n", path, err)
		return false
	}
	return true
}
