#+vet explicit-allocators
package wopt

import "core:slice"
import "core:mem"
import "core:os"
import "core:strings"
import "core:fmt"
import "core:container/xar"

import B "../base"

// Types

// NOTE: Type_Id's can only be compared equal and are non-deterministic
//       They represent an offset into the interner static memory
//       There is no guarantee that there are any Type_Id's besides this one, do not assume such a guarantee
Type_Id :: distinct uint

// NOTE: No integer type is signed or unsigned, operations define signedness, not type
Builtin_Type :: enum {
	I32,
}

Type_Kind :: enum u8 {
	// Empty/No type
	None,
	// Memory type, some values return this or return a tuple which contains a memory.
	// Memory is used for side effects, this should never be generated by the frontend, only used.
	Memory,
	// Tuple type for functions with return values. (members[0], mem)
	// Only members[0] is used, the other value is always implicitly a mem
	Memory_Tuple,
	// Class of builtin types
	Builtin,
}

// The actual key of the type, what makes the type unique
Type_Key :: struct {
	kind:    Type_Kind,
	members: []Type_Id,
}

type_key_equal :: proc(a, b: Type_Key) -> bool {
	if a.kind != b.kind {
		return false
	}

	return slice.equal(a.members, b.members)
}

type_key_make :: proc(arena: ^B.Arena, kind: Type_Kind, members: ..Type_Id) -> (key: Type_Key) {
	key.kind    = kind
	key.members = B.arena_push_make(arena, []Type_Id, len(members))
	copy(key.members, members)
	return
}

Type :: struct {
	using key: Type_Key,

	id:    Type_Id,
	size:  int,
	align: int,
}

builtin_type_types := [Builtin_Type]Type{
	.I32 = { kind = .Builtin, size = 4, align = 4 },
}

type_create :: proc(key: Type_Key) -> (t: Type) {
	t.key = key

	return
}

type_add :: proc(m: ^Module, type: Type) -> (id: Type_Id) {
	id           = Type_Id(xar.len(m.types))
	type_ptr, _ := xar.append_and_get_ptr(&m.types, type)
	type_ptr.id  = id

	return
}

type_get_builtin :: proc(m: ^Module, builtin: Builtin_Type) -> (id: Type_Id) {
	return m.bultin_types[builtin]
}

type_get_none :: proc(m: ^Module) -> (id: Type_Id) {
	return
}

type_get :: proc(m: ^Module, id: Type_Id) -> ^Type {
	return xar.get_ptr(&m.types, id)
}

// Functions

Function_Id :: distinct u32

Function_Flag :: enum {
	// Internal flags
	_Frozen,
}

Function_Flags :: bit_set[Function_Flag]

Function_Body :: struct {
	blocks: []Block,
	values: []Value,
	start:  Block_Id,
}

Function :: struct {
	id:         Function_Id,
	name:       string,
	flags:      Function_Flags,
	parameters: []Type_Id,
	result:     Type_Id,

	// TODO(robin): Improve comment
	// NOTE(robin): When .Frozen in flags && .Never_Inline in flags then this can never change again. A copy has to be made instead
	//              This is so that inlining can use an IR representation of this function without building a
	//              compile time dependency tree on the functions, which would make threading less effective
	//              this is a tradeoff made with performance, simplicity and optimization in optimization in mind
	//              while it does make inlining a bit worse (we inline an unoptimized function, which could increase the inline
	//              cost for useless code), we gain faster compile times by not having dependencies on other functions at compile
	//              time, also it allows for a much simpler threading model
	//              we will probably introduce a hard max inline cost size, which would allow us to optimize large functions
	//              to not have to copy all of it
	build_body:   Function_Body,
	compile_body: Function_Body,
}

function_add :: proc(m: ^Module, function: Function) -> (id: Function_Id) {
	id               = Function_Id(xar.len(m.functions))
	function_ptr, _ := xar.append_and_get_ptr(&m.functions, function)
	function_ptr.id  = id

	function_ptr.parameters = B.arena_push_make(m.arena, []Type_Id, len(function.parameters))
	copy(function_ptr.parameters, function.parameters)

	function_ptr.name, _ = strings.intern_get(&m.interner, function.name)
	return
}

// Module

Module :: struct {
	arena:    ^B.Arena,
	interner: strings.Intern,

	// Types
	types:        xar.Array(Type, 4),
	bultin_types: [Builtin_Type]Type_Id,

	// Functions
	functions: xar.Array(Function, 4),
}

module_new :: proc() -> (m: ^Module) {
	m = B.arena_bootstrap_new(Module, "arena")

	xar.init(&m.functions, B.arena_allocator(m.arena))
	xar.init(&m.types, B.arena_allocator(m.arena))

	// NOTE: We use the heap allocator for the map, because storing a long lived map
	//       inside an arena wastes ~100%
	//       the strings themselves are ok to be stored in the arena
	strings.intern_init(&m.interner, B.arena_allocator(m.arena), os.heap_allocator())

	assert(type_add(m, {}) == 0)
	type_add(m, { kind = .Memory })

	for type in Builtin_Type {
		m.bultin_types[type] = type_add(m, builtin_type_types[type])
	}

	return
}

module_free :: proc(m: ^Module) {
	strings.intern_destroy(&m.interner)
	B.arena_destroy(m.arena)
}

main :: proc() {
	track: mem.Tracking_Allocator
	mem.tracking_allocator_init(&track, context.allocator, context.allocator)
	context.allocator = mem.tracking_allocator(&track)

	defer {
		if len(track.allocation_map) > 0 {
			fmt.eprintfln("=== %v allocations not freed: ===", len(track.allocation_map))
			for _, entry in track.allocation_map {
				fmt.eprintfln("- %v bytes @ %v", entry.size, entry.location)
			}
		}
		mem.tracking_allocator_destroy(&track)
	}

	m := module_new()
	defer module_free(m)

	function_add(m, Function { name = "main", parameters = { type_get_builtin(m, .I32) } })

	fmt.println("Types:")
	for it := xar.iterator(&m.types); type in xar.iterate_by_val(&it) {
		fmt.printfln("  - Kind = %v, Id = %v, size = %x, align = %x", type.kind, type.id, type.size, type.align)
	}
	fmt.println("Functions:")
	for it := xar.iterator(&m.functions); function in xar.iterate_by_val(&it) {
		fmt.printfln("  %q: Id = %v, params = %v, result = %v", function.name, function.id, function.parameters, function.result)
	}
}
