#+vet explicit-allocators
package wopt

import "core:mem"
import "core:slice"

import B "../base"

// Types

// NOTE: Type_Id's can only be compared equal and are non-deterministic
//       They represent a compressed offset into the interner static memory
//       There is no guarantee that there are any Type_Id's + 1 after this one, do not assume such a guarantee
Type_Id :: distinct uint

Type_Kind :: enum u8 {
	// Empty/No type
	None,

	// Integers, they are not signed/unsigned, operations determine the signedness
	I32,

	// Memory type, some values return this or return a tuple which contains a memory.
	// Memory is used for side effects, this should never be generated by the frontend, only used.
	Memory,

	Struct,
}

Type_Member :: struct {
	offset: int,
	type:   Type_Id,
}

// The actual key of the type, what makes the type unique
Type_Key :: struct {
	kind:    Type_Kind,
	size:    int,
	align:   int,
	members: []Type_Member,
}

type_key_equal :: proc(a, b: Type_Key) -> bool {
	if a.kind != b.kind {
		return false
	}

	if a.size != b.size {
		return false
	}

	if a.align != b.align {
		return false
	}

	return slice.equal(a.members, b.members)
}

type_key_struct_simple :: proc(arena: ^B.Arena, members: ..Type) -> (key: Type_Key) {
	key.kind    = .Struct
	key.members = B.arena_push_make(arena, []Type_Member, len(members))
	key.align   = 1 // ensure alignment higher than 0

	offset := 0
	for member_type, i in members {
		offset          = mem.align_forward_int(offset, member_type.align)
		key.members[i]  = { offset, member_type.id }
		offset         += member_type.size

		key.align = max(key.align, member_type.align)
		assert(0 <= offset)
	}

	key.size = mem.align_forward_int(offset, key.align)

	return
}

type_none :: proc(m: ^Module) -> Type_Id {
	// TODO(robin): check if this is actually of any value
	//              idea is to make llvm optimize most of the shit out, but I don't really see if that makes sense
	return #force_inline type_intern(m, {})
}

type_i32 :: proc(m: ^Module) -> Type_Id {
	return type_intern(m, { kind = .I32, size = 4, align = 4 })
}

type_mem :: proc(m: ^Module) -> Type_Id {
	return type_intern(m, { kind = .Memory })
}

type_struct_simple :: proc(m: ^Module, members: ..Type_Id) -> Type_Id {
	temp := B.TEMP_ALLOCATOR_GUARD()

	member_types := B.arena_push_make(temp, []Type, len(members))
	for &member_type, i in member_types {
		member_type = type_get(m, members[i])
	}

	return type_intern(m, type_key_struct_simple(temp, ..member_types))
}

type_struct :: proc(m: ^Module, size, align: int, members: ..Type_Member) -> Type_Id {
	return type_intern(m, { kind = .Struct, size = size, align = align, members = members })
}

Type :: struct {
	using key: Type_Key,

	id: Type_Id,
}

type_create :: proc(key: Type_Key) -> (t: Type) {
	t.key = key

	return
}

type_intern :: proc(m: ^Module, key: Type_Key) -> (id: Type_Id) {
	if m.frozen {
		panic("`type_intern` is only available for unfrozen modules due to the builder api being multi threaded")
	}

	return type_interner_intern(m.type_interner, &m.type_interner_arena, key)
}

type_get :: proc(m: ^Module, id: Type_Id) -> Type {
	return type_interner_load(m.type_interner, id)
}
