#+vet explicit-allocators
package wopt

import "core:slice"
import "core:mem"
import "core:os"
import "core:strings"
import "core:fmt"
import "core:container/xar"

import B "../base"

// Types

// NOTE: Type_Id's can only be compared equal and are non-deterministic
//       They represent a compressed offset into the interner static memory
//       There is no guarantee that there are any Type_Id's + 1 after this one, do not assume such a guarantee
Type_Id :: distinct uint

Type_Kind :: enum u8 {
	// Empty/No type
	None,

	// Integers, they are not signed/unsigned, operations determine the signedness
	I32,

	// Memory type, some values return this or return a tuple which contains a memory.
	// Memory is used for side effects, this should never be generated by the frontend, only used.
	Memory,

	// Basically equivalent to a struct {members[0]?, Memory}
	// Only valid type for return values
	// Represents only Memory if len(members) <= 0
	Result,

	Struct,
}

Type_Member :: struct {
	offset: int,
	type:   Type_Id,
}

// The actual key of the type, what makes the type unique
Type_Key :: struct {
	kind:    Type_Kind,
	size:    int,
	align:   int,
	members: []Type_Member,
}

type_key_equal :: proc(a, b: Type_Key) -> bool {
	if a.kind != b.kind {
		return false
	}

	if a.size != b.size {
		return false
	}

	if a.align != b.align {
		return false
	}

	return slice.equal(a.members, b.members)
}

type_key_make :: proc(m: ^Module, arena: ^B.Arena, kind: Type_Kind, members: ..Type_Member, loc := #caller_location) -> (key: Type_Key) {
	key.kind    = kind
	key.members = B.arena_push_make(arena, []Type_Member, len(members))
	copy(key.members, members)

	switch key.kind {
	case .None:
		assert(len(members) == 0, loc = loc)

	case .I32:
		assert(len(members) == 0, loc = loc)
		key.align, key.size = 4, 4

	case .Memory: assert(len(members) == 0)

	case .Result:
		assert(len(members) == 1, loc = loc)

		type := type_get(m, key.members[0].type)
		key.align, key.size = type.align, type.size
	
	case .Struct: // TODO(robin): implement default struct layout calculation
	}
	return
}

Type :: struct {
	using key: Type_Key,

	id: Type_Id,
}

type_create :: proc(key: Type_Key) -> (t: Type) {
	t.key = key

	return
}

type_intern_make :: proc(m: ^Module, kind: Type_Kind, members: ..Type_Member, loc := #caller_location) -> (id: Type_Id) {
	

	return
}

type_intern_key :: proc(m: ^Module, key: Type_Key) -> (id: Type_Id) {
	if m.frozen {
		panic("`type_intern` is only available for unfrozen modules due to the builder api being multi threaded")
	}

	return type_interner_intern(m.type_interner, &m.type_interner_arena, key)
}

type_intern :: proc{
	type_intern_make,
	type_intern_key,
}

// type_get_builtin :: proc(m: ^Module, builtin: Builtin_Type) -> (id: Type_Id) {
// 	return m.bultin_types[builtin]
// }

type_get_none :: proc(m: ^Module) -> (id: Type_Id) {
	return
}

type_get :: proc(m: ^Module, id: Type_Id) -> Type {
	return type_interner_load(m.type_interner, id)
}

// Functions

Function_Id :: distinct u32

Function_Flag :: enum {
	// Internal flags
}

Function_Flags :: bit_set[Function_Flag]

Function_Body :: struct {
	blocks: []Block,
	values: []Value,
	start:  Block_Id,
}

Function :: struct {
	id:         Function_Id,
	name:       string,
	flags:      Function_Flags,
	parameters: []Type_Id,
	result:     Type_Id,

	// TODO(robin): Improve comment
	// NOTE(robin): When the module is frozen and .Never_Inline in flags then this can never change again. A copy has to be made instead
	//              This is so that inlining can use an IR representation of this function without building a
	//              compile time dependency tree on the functions, which would make threading less effective
	//              this is a tradeoff made with performance, simplicity and optimization in optimization in mind
	//              while it does make inlining a bit worse (we inline an unoptimized function, which could increase the inline
	//              cost for useless code), we gain faster compile times by not having dependencies on other functions at compile
	//              time, also it allows for a much simpler threading model
	//              we will probably introduce a hard max inline cost size, which would allow us to optimize large functions
	//              to not have to copy all of it
	build_body:   Function_Body,
	compile_body: Function_Body,
}

function_add :: proc(m: ^Module, function: Function) -> (id: Function_Id) {
	id               = Function_Id(xar.len(m.functions))
	function_ptr, _ := xar.append_and_get_ptr(&m.functions, function)
	function_ptr.id  = id

	function_ptr.parameters = B.arena_push_make(m.arena, []Type_Id, len(function.parameters))
	copy(function_ptr.parameters, function.parameters)

	function_ptr.name, _ = strings.intern_get(&m.interner, function.name)
	return
}

// Module

Module :: struct {
	arena:    ^B.Arena,
	interner: strings.Intern,
	frozen:   bool,

	// Types
	type_interner:       ^Type_Interner,
	type_interner_arena: Type_Interner_Thread_Arena, // WARN: only vaild in !frozen

	// Functions
	functions: xar.Array(Function, 4),
}

module_new :: proc() -> (m: ^Module) {
	m = B.arena_bootstrap_new(Module, "arena")

	xar.init(&m.functions, B.arena_allocator(m.arena))
	m.type_interner = type_interner_new()

	// NOTE: We use the heap allocator for the map, because storing a long lived map
	//       inside an arena wastes ~100%
	//       the strings themselves are ok to be stored in the arena
	strings.intern_init(&m.interner, B.arena_allocator(m.arena), os.heap_allocator())

	// assert(type_intern(m, {}) != 0)
	type_intern_key(m, { kind = .Memory })

	return
}

module_free :: proc(m: ^Module) {
	type_interner_free(m.type_interner)
	strings.intern_destroy(&m.interner)
	B.arena_destroy(m.arena)
}

module_freeze_for_build :: proc(m: ^Module) {
	m.frozen = true
}

main :: proc() {
	track: mem.Tracking_Allocator
	mem.tracking_allocator_init(&track, context.allocator, context.allocator)
	context.allocator = mem.tracking_allocator(&track)

	defer {
		if len(track.allocation_map) > 0 {
			fmt.eprintfln("=== %v allocations not freed: ===", len(track.allocation_map))
			for _, entry in track.allocation_map {
				fmt.eprintfln("- %v bytes @ %v", entry.size, entry.location)
			}
		}
		mem.tracking_allocator_destroy(&track)
	}

	m := module_new()
	defer module_free(m)

	function_add(m, Function { name = "main", parameters = { type_intern_key(m, { kind = .I32 }) } })

	// fmt.println("Types:")
	// for it := xar.iterator(&m.types); type in xar.iterate_by_val(&it) {
	// 	fmt.printfln("  - Kind = %v, Id = %v, size = %x, align = %x", type.kind, type.id, type.size, type.align)
	// }
	// fmt.println("Functions:")
	// for it := xar.iterator(&m.functions); function in xar.iterate_by_val(&it) {
	// 	fmt.printfln("  %q: Id = %v, params = %v, result = %v", function.name, function.id, function.parameters, function.result)
	// }
}
