// Code generated by wopt/c_gen. DO NOT EDIT.
package cgen_example

import "base:runtime"

Cgen_example_String :: struct { data: ^u8, len: uintptr }
Cgen_example_Slice_Member :: struct { data: ^Cgen_example_Member, len: uintptr }
Cgen_example_Slice_u8 :: struct { data: ^u8, len: uintptr }
Cgen_example_Slice_i32 :: struct { data: ^i32, len: uintptr }
Cgen_example_Object_Id :: Object_Id
Cgen_example_Kind :: Kind
Cgen_example_Flag :: Flag
Cgen_example_Flags :: Flags
Cgen_example_Padded :: Padded
Cgen_example_Nested :: Nested
Cgen_example_Object :: Object
Cgen_example_Record :: Record
Cgen_example_Member :: Member
Cgen_example_Summary :: Summary
Cgen_example_Mixed :: Mixed
Cgen_example_Tail :: Tail
Cgen_example_pair_string_bytes_Result :: struct { r0: Cgen_example_String, r1: Cgen_example_Slice_u8, }
Cgen_example_split_Result :: struct { r0: i32, r1: i32, }

@(export, link_name="cgen_example_object_new")
cgen_export_object_new :: proc "c" (id: Cgen_example_Object_Id) -> ^Cgen_example_Object {
    context = runtime.default_context()
    result := object_new(id)
    return result
}

@(export, link_name="cgen_example_object_free")
cgen_export_object_free :: proc "c" (object: ^Cgen_example_Object) {
    context = runtime.default_context()
    object_free(object)
}

@(export, link_name="cgen_example_object_kind")
cgen_export_object_kind :: proc "c" (object: ^Cgen_example_Object, kind: Cgen_example_Kind, flags: Cgen_example_Flags) -> u32 {
    context = runtime.default_context()
    result := object_kind(object, kind, flags)
    return result
}

@(export, link_name="cgen_example_sum_bytes")
cgen_export_sum_bytes :: proc "c" (bytes: Cgen_example_Slice_u8) -> u32 {
    context = runtime.default_context()
    result := sum_bytes(([^]u8)(bytes.data)[:int(bytes.len)])
    return result
}

@(export, link_name="cgen_example_sum_variadic")
cgen_export_sum_variadic :: proc "c" (values: Cgen_example_Slice_i32) -> i32 {
    context = runtime.default_context()
    result := sum_variadic(..(([^]i32)(values.data)[:int(values.len)]))
    return result
}

@(export, link_name="cgen_example_sum_with_flags")
cgen_export_sum_with_flags :: proc "c" (a: i32, b: i32, values: Cgen_example_Slice_i32, flags: Cgen_example_Flags) -> i32 {
    context = runtime.default_context()
    result := sum_with_flags(a, b, ..(([^]i32)(values.data)[:int(values.len)]), flags = flags)
    return result
}

@(export, link_name="cgen_example_echo_bytes")
cgen_export_echo_bytes :: proc "c" (value: Cgen_example_String) -> Cgen_example_String {
    context = runtime.default_context()
    result := echo_bytes(string(([^]u8)(value.data)[:int(value.len)]))
    return Cgen_example_String{data = cast(^u8)raw_data(result), len = uintptr(len(result))}
}

@(export, link_name="cgen_example_identity_bytes")
cgen_export_identity_bytes :: proc "c" (value: Cgen_example_Slice_u8) -> Cgen_example_Slice_u8 {
    context = runtime.default_context()
    result := identity_bytes(([^]u8)(value.data)[:int(value.len)])
    return Cgen_example_Slice_u8{data = cast(^u8)raw_data(result), len = uintptr(len(result))}
}

@(export, link_name="cgen_example_pair_string_bytes")
cgen_export_pair_string_bytes :: proc "c" (value: Cgen_example_String, bytes: Cgen_example_Slice_u8) -> Cgen_example_pair_string_bytes_Result {
    context = runtime.default_context()
     r0,  r1 := pair_string_bytes(string(([^]u8)(value.data)[:int(value.len)]), ([^]u8)(bytes.data)[:int(bytes.len)])
    return Cgen_example_pair_string_bytes_Result{Cgen_example_String{data = cast(^u8)raw_data(r0), len = uintptr(len(r0))}, Cgen_example_Slice_u8{data = cast(^u8)raw_data(r1), len = uintptr(len(r1))}}
}

@(export, link_name="cgen_example_move_padded")
cgen_export_move_padded :: proc "c" (value: Cgen_example_Padded) -> Cgen_example_Padded {
    context = runtime.default_context()
    result := move_padded(value)
    return result
}

@(export, link_name="cgen_example_move_padded_ptr")
cgen_export_move_padded_ptr :: proc "c" (value: ^Cgen_example_Padded, output: ^Cgen_example_Padded) {
    context = runtime.default_context()
    move_padded_ptr(value, output)
}

@(export, link_name="cgen_example_move_nested")
cgen_export_move_nested :: proc "c" (value: Cgen_example_Nested) -> Cgen_example_Nested {
    context = runtime.default_context()
    result := move_nested(value)
    return result
}

@(export, link_name="cgen_example_move_nested_ptr")
cgen_export_move_nested_ptr :: proc "c" (value: ^Cgen_example_Nested, output: ^Cgen_example_Nested) {
    context = runtime.default_context()
    move_nested_ptr(value, output)
}

@(export, link_name="cgen_example_split")
cgen_export_split :: proc "c" (value: i32) -> Cgen_example_split_Result {
    context = runtime.default_context()
     r0,  r1 := split(value)
    return Cgen_example_split_Result{r0, r1}
}

@(export, link_name="cgen_example_record_identity")
cgen_export_record_identity :: proc "c" (record: Cgen_example_Record) -> Cgen_example_Record {
    context = runtime.default_context()
    result := record_identity(record)
    return result
}

@(export, link_name="cgen_example_member_sum")
cgen_export_member_sum :: proc "c" (members: Cgen_example_Slice_Member) -> uint {
    context = runtime.default_context()
    result := member_sum(..(([^]Member)(members.data)[:int(members.len)]))
    return result
}

@(export, link_name="cgen_example_mixed_identity")
cgen_export_mixed_identity :: proc "c" (value: Cgen_example_Mixed) -> Cgen_example_Mixed {
    context = runtime.default_context()
    result := mixed_identity(value)
    return result
}

@(export, link_name="cgen_example_tail_identity")
cgen_export_tail_identity :: proc "c" (value: Cgen_example_Tail) -> Cgen_example_Tail {
    context = runtime.default_context()
    result := tail_identity(value)
    return result
}

@(export, link_name="cgen_example_mixed_pointer")
cgen_export_mixed_pointer :: proc "c" (value: ^Cgen_example_Mixed, output: ^Cgen_example_Mixed) {
    context = runtime.default_context()
    mixed_pointer(value, output)
}

@(export, link_name="cgen_example_tail_pointer")
cgen_export_tail_pointer :: proc "c" (value: ^Cgen_example_Tail, output: ^Cgen_example_Tail) {
    context = runtime.default_context()
    tail_pointer(value, output)
}
