// Code generated by wopt/c_gen. DO NOT EDIT.
#ifndef CGEN_EXAMPLE_CGEN_H
#define CGEN_EXAMPLE_CGEN_H
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

typedef struct Cgen_example_String { const uint8_t *data; uintptr_t len; } Cgen_example_String;
typedef struct Cgen_example_Padded Cgen_example_Padded;
typedef struct Cgen_example_Nested Cgen_example_Nested;
typedef struct Cgen_example_Object Cgen_example_Object;
typedef struct Cgen_example_Record Cgen_example_Record;
typedef struct Cgen_example_Member Cgen_example_Member;
typedef struct Cgen_example_Summary Cgen_example_Summary;
typedef struct Cgen_example_Mixed Cgen_example_Mixed;
typedef struct Cgen_example_Tail Cgen_example_Tail;
typedef uintptr_t Cgen_example_Object_Id;
typedef intptr_t Cgen_example_Kind;
#define Cgen_example_Kind_None ((Cgen_example_Kind)(0))
#define Cgen_example_Kind_Ready ((Cgen_example_Kind)(1))
#define Cgen_example_Kind_Done ((Cgen_example_Kind)(2))
typedef intptr_t Cgen_example_Flag;
#define Cgen_example_Flag_A ((Cgen_example_Flag)(4))
#define Cgen_example_Flag_B ((Cgen_example_Flag)(5))
#define Cgen_example_Flag_C ((Cgen_example_Flag)(6))
typedef uint8_t Cgen_example_Flags;
#define Cgen_example_Flags_A ((Cgen_example_Flags)(UINT8_C(1) << 0))
#define Cgen_example_Flags_B ((Cgen_example_Flags)(UINT8_C(1) << 1))
#define Cgen_example_Flags_C ((Cgen_example_Flags)(UINT8_C(1) << 2))
typedef struct Cgen_example_Slice_Member { const Cgen_example_Member *data; uintptr_t len; } Cgen_example_Slice_Member;
typedef struct Cgen_example_Slice_u8 { const uint8_t *data; uintptr_t len; } Cgen_example_Slice_u8;
typedef struct Cgen_example_Slice_i32 { const int32_t *data; uintptr_t len; } Cgen_example_Slice_i32;
struct Cgen_example_Padded {
    uint8_t a;
    uint64_t b;
};
struct Cgen_example_Nested {
    Cgen_example_Padded inner;
    int32_t count;
};
struct Cgen_example_Summary {
    intptr_t count;
};
struct Cgen_example_Record {
    Cgen_example_String name;
    Cgen_example_Slice_Member members;
    Cgen_example_Summary summary;
};
struct Cgen_example_Member {
    intptr_t offset;
    Cgen_example_Object_Id id;
};
struct Cgen_example_Mixed {
    float a;
    double b;
};
struct Cgen_example_Tail {
    double a;
    float b;
};
typedef struct Cgen_example_pair_string_bytes_Result {
    Cgen_example_String r0;
    Cgen_example_Slice_u8 r1;
} Cgen_example_pair_string_bytes_Result;
typedef struct Cgen_example_split_Result {
    int32_t r0;
    int32_t r1;
} Cgen_example_split_Result;

Cgen_example_Object * cgen_example_object_new(Cgen_example_Object_Id id);
void cgen_example_object_free(Cgen_example_Object * object);
uint32_t cgen_example_object_kind(Cgen_example_Object * object, Cgen_example_Kind kind, Cgen_example_Flags flags);
uint32_t cgen_example_sum_bytes(Cgen_example_Slice_u8 bytes);
int32_t cgen_example_sum_variadic(Cgen_example_Slice_i32 values);
int32_t cgen_example_sum_with_flags(int32_t a, int32_t b, Cgen_example_Slice_i32 values, Cgen_example_Flags flags);
Cgen_example_String cgen_example_echo_bytes(Cgen_example_String value);
Cgen_example_Slice_u8 cgen_example_identity_bytes(Cgen_example_Slice_u8 value);
Cgen_example_pair_string_bytes_Result cgen_example_pair_string_bytes(Cgen_example_String value, Cgen_example_Slice_u8 bytes);
Cgen_example_Padded cgen_example_move_padded(Cgen_example_Padded value);
void cgen_example_move_padded_ptr(Cgen_example_Padded * value, Cgen_example_Padded * output);
Cgen_example_Nested cgen_example_move_nested(Cgen_example_Nested value);
void cgen_example_move_nested_ptr(Cgen_example_Nested * value, Cgen_example_Nested * output);
Cgen_example_split_Result cgen_example_split(int32_t value);
Cgen_example_Record cgen_example_record_identity(Cgen_example_Record record);
uintptr_t cgen_example_member_sum(Cgen_example_Slice_Member members);
Cgen_example_Mixed cgen_example_mixed_identity(Cgen_example_Mixed value);
Cgen_example_Tail cgen_example_tail_identity(Cgen_example_Tail value);
void cgen_example_mixed_pointer(Cgen_example_Mixed * value, Cgen_example_Mixed * output);
void cgen_example_tail_pointer(Cgen_example_Tail * value, Cgen_example_Tail * output);
#endif
